name = "tax-payment-backend"
compatibility_date = "2026-04-19"
main = "src/index.ts"
workers_dev = false



[[services]]
binding = "BOT"
service = "telegram-bot-router"

[[d1_databases]]
binding = "DB"
database_name = "tax-payment-manager-db"
database_id = "9c248574-762f-45b1-898c-f5b2328d7fab"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tax-manager-storage"
